### ISSUE TITLE
Memory usage exceeds limit on Colab

### ISSUE THREAD

**Issue by Cklwanfifa** [ContinualAI/clvision-challenge-2023#7] opened 2023-04-12 12:43 UTC
Hi, I tried to run the example file on Colab and it seems that the GPU memory allocation exceeded the maximum allowed amount.

`Traceback (most recent call last):
  File "/content/clvision-challenge-2023/train.py", line 134, in <module>
    main(args)
  File "/content/clvision-challenge-2023/train.py", line 95, in main
    cl_strategy.train(experience, num_workers=args.num_workers)
  File "/content/clvision-challenge-2023/avalanche/avalanche/training/templates/base_sgd.py", line 146, in train
    super().train(experiences, eval_streams, **kwargs)
  File "/content/clvision-challenge-2023/avalanche/avalanche/training/templates/base.py", line 117, in train
    self._after_training_exp(**kwargs)
  File "/content/clvision-challenge-2023/avalanche/avalanche/training/templates/base.py", line 233, in _after_training_exp
    trigger_plugins(self, "after_training_exp", **kwargs)
  File "/content/clvision-challenge-2023/avalanche/avalanche/training/utils.py", line 35, in trigger_plugins
    getattr(p, event)(strategy, **kwargs)
  File "/content/clvision-challenge-2023/utils/competition_plugins.py", line 73, in after_training_exp
    raise MaxGPUAllocationExceeded(ram_allocated, self.max_allowed)
utils.competition_plugins.MaxGPUAllocationExceeded: GPU memory allocation (4297 MB) exceeded the maximum allowed amount which is 4000 MB.`

**Comment by HamedHemati** [comment] 2023-04-12 19:39
Hi @Cklwanfifa 

Did you increase the batch size or the other settings?
I tried the same code on Colab before and it worked fine. At which epoch did this happen and what GPU is assigned to you when using Colab?

**Comment by Cklwanfifa** [comment] 2023-04-13 00:37
I didn't do any modification on the settings.
You can access it through
https://colab.research.google.com/drive/1BBB6J0JBj1_6nxOd2OxqARe3v226nI69?usp=sharing

**Comment by HamedHemati** [comment] 2023-04-13 12:29
> I didn't do any modification on the settings.
> You can access it through
> https://colab.research.google.com/drive/1BBB6J0JBj1_6nxOd2OxqARe3v226nI69?usp=sharing

Thanks for sharing the Colab notebook. I also tried it and got the same error. But the interesting part is that the max GPU usage (also including the GPU cache) was around 1.2 GBs just before the training process crashed:

<img width="450" alt="colab_suage" src="https://user-images.githubusercontent.com/11629528/231754735-33cfad7f-5593-4ed3-826e-2fc0a6d6004a.png">

I can't remember what GPU I got the last time I ran the code, but this issue could be caused by the `GPUtil` package and its compatibility with Tesla series, but I'm still not sure. We haven't had this problem for local GPUs so far. For now, you can manually increase the max GPU allocation threshold and run your experiments until we find the reason. For most cases the true GPU allocation shouldn't exceed the competition threshold since the threshold is pretty lenient, so no need to worry for most cases with batch size 64, unless you want to implement a strategy that requires frequent parameter replications or huge batch sizes.

**Comment by Cklwanfifa** [comment] 2023-04-15 08:21
I found a local A100 GPU and ran the example code. At the first checkpoint it showed that

`MAX GPU MEMORY ALLOCATED: 119 MB
MAX RAM ALLOCATED: 5874 MB`

I assume that:
1. The RAMchecker (not the GPUMemoryChecker) got the incorrect RAM data. 
2. The error information provided by competition_plugins might be wrong.

**Comment by HamedHemati** [comment] 2023-04-16 19:46
> I found a local A100 GPU and ran the example code. At the first checkpoint it showed that
> 
> `MAX GPU MEMORY ALLOCATED: 119 MB MAX RAM ALLOCATED: 5874 MB`
> 
> I assume that:
> 
> 1. The RAMchecker (not the GPUMemoryChecker) got the incorrect RAM data.
> 2. The error information provided by competition_plugins might be wrong.

Thanks for the update.  The RAM usage for me is between 2-2.5 GBs for the first few epochs on Mac and Linux. Similar to the GPU limit, you can manually change the limit for your experiments. We will try to find a solution for the hardware usage inconsistency.

**Comment by ShiWuxuan** [comment] 2023-04-17 14:24
@HamedHemati Hi, I also have a question about the GPUMemoryChecker. The memory usage output from the GPUMemoryChecker does not match the results I see using the gpustat command, and I want to know which one ultimately prevails?
The first image is the output of GPUMemoryChecker, and the second image is the gpu usage displayed using the gpustat command.
![checker](https://user-images.githubusercontent.com/61214471/232516789-10d05e35-7702-47ed-885c-005484ede5c2.png)
![gpustat](https://user-images.githubusercontent.com/61214471/232516818-4e31e2e6-8769-491c-9d73-6daf423827b4.png)

**Comment by HamedHemati** [comment] 2023-04-17 20:10
@ShiWuxuan Thanks for sharing the usage report. It seems like the only way to get the actual GPU memory usage in a consistent way is to use the `nvidia-smi` package. The RAM usage is also not consistent across different operating systems. 

One solution is to use the `nvidia-smi` package, but that would also cause issues if someone tries to use a shared GPU. Therefore, we will most probably remove the RAM and GPU usage plugins, and will ask the participants to check the GPU memory usage manually (with the current limits).  We will only keep the time checker plugin just to have an approximate training time limit for the strategies.

**Comment by ShiWuxuan** [comment] 2023-04-18 05:56
Thank you for your detailed reply. The GPU memory usage reported by `nvidia-smi` package is shown in the picture below. This is the result without changing the code, i.e. `Navie` strategy + `EWCPlugin` + `LwFPlugin` with `batch_size=64`. Even with such a simple strategy, the GPU memory used already exceeds the given limit of 1000MB. Perhaps the previous limit was set based on the output of the `GPUMemoryChecker`. May I ask if the GPU memory limit will be relaxed, which is important for method design.
![image](https://user-images.githubusercontent.com/61214471/232684178-13a49cbf-9d4f-4d29-aa67-6bb0c077112b.png)

**Comment by HamedHemati** [comment] 2023-04-18 06:23
That's correct, sorry for the confusion. I got mixed up between the current limits for the RAM usage and the  GPU memory usage limits. The new GPU usage limit will be 4000 MBs and the limit for the RAM usage will be removed. I hope this solves the hardware restriction issues across different platforms.

**Comment by ShiWuxuan** [comment] 2023-04-18 06:54
I get it, thanks for the explanation.

**Comment by HamedHemati** [comment] 2023-04-18 17:42
GPU and RAM usage plugins are removed in the latest version of the code. I'm closing this issue.

**Closed as completed by HamedHemati** 2023-04-18 17:42 UTC
